### ISSUE TITLE
Bug Report: Notes arent registered as pressed.

### ISSUE THREAD

**Issue by TheRealJake12** [BoloVEVO/Kade-Engine-Public#19]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10
## What version of the game are you using? Look in the bottom left corner of the main menu.
Latest Commit (1.5?)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
You open a song and thats it
## Please describe your issue. Provide extensive detail and images if possible.
You cant press notes

https://user-images.githubusercontent.com/84357907/187544252-5d5f5dcd-3231-4975-ad6d-205ebd60be68.mp4

**Comment by BoloVEVO** [comment]
What 💀💀. Have you checked the judgement settings?

**Comment by TheRealJake12** [comment]
yes

**Comment by TheRealJake12** [comment]
only happens in latest commit and not on 1.4.2

**Comment by TheRealJake12** [comment]
really fuckin weird I reset my settings and it works. Havent updated the build since the latest commit
