### ISSUE TITLE
Bug Report: Modcharts arent recognized if the song name is 2 words

### ISSUE THREAD

**Issue by TheRealJake12** [BoloVEVO/Kade-Engine-Public#21]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4.2 and latest commit have this issue
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Add song that has 2 words (lets call the song "Your Mother".
## Please describe your issue. Provide extensive detail and images if possible.
Your mother has a modchart in its files. It does not detect the modchart and does not run the modchart.

**Comment by Wither362** [comment]
I think it’s because in the files the folder name shouldn’t be _"Your Mother"_, or _"your mother"_, it should be _"your-mother"_, replacing the spaces by _"-"_

**Comment by TheRealJake12** [comment]
thats what it is its your-mother

**Comment by Wither362** [comment]
> thats what it is its your-mother

Oh, let me see what I can do to fix it

**Comment by BoloVEVO** [comment]
If you're trying to put a modchart without compiling with it (basically dragging the modchart into the song json in the compiled build) the modchart won't be detected. Put the modchart in your assets of your project and then compile it and it'll work.

**Comment by TheRealJake12** [comment]
nah it was because you gotta make it check for songId instead

**Comment by TheRealJake12** [comment]
I fixed it
