### ISSUE TITLE
Bug Report: Exiting the stage editor removes the bg in PlayState

### ISSUE THREAD

**Issue by TheRealJake12** [BoloVEVO/Kade-Engine-Public#25]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10 (little outdated version though)
## What version of the game are you using? Look in the bottom left corner of the main menu.
Was latest commit I havent tested the newer stuff
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
yea build to debug and go to the stage editor.
## Please describe your issue. Provide extensive detail and images if possible.
 It removes the stage (Its prolly the clearStoredMemory function)

**Comment by glowsoony** [comment]
what version are you using?

**Comment by TheRealJake12** [comment]
latest. This is because the clearStoredMemory function removes the bg stuff

**Comment by glowsoony** [comment]
> latest. This is because the clearStoredMemory function removes the bg stuff

weird, as it has never happend to me before.

**Comment by BoloVEVO** [comment]
I'm gonna delete stage editor because it's kinda buggy and I'll make a substate of PlayState intead.
