### ISSUE TITLE
Bug Report: Sustains broken (Idk if fix will be later)

### ISSUE THREAD

**Issue by glowsoony** [BoloVEVO/Kade-Engine-Public#33]
When the option "Post Process Song Notes" is on the sustains are fine in 1x speed while when changing to any other speed will bug out the sustains.

Example #1 When The Option Is Off: https://streamable.com/mt4ezf
In 1x speed and 1.2x speed both the sustains are fine. (when the option is _OFF_)

Example #2 When The Option Is On: https://streamable.com/0c7wta
In 1x the sustains are fine, but in rate 1.2x speed the sustains break. (when the option is _ON_)

Please tell me if it's just the fact that I did some code wrong and it's not the main code.

**Comment by BoloVEVO** [comment]
Already fixed. Forgot to push, I'm busy rn

**Comment by glowsoony** [comment]
> Already fixed. Forgot to push, I'm busy rn

thank you so much.
