### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by SerapioDeAlicante** [BoloVEVO/Kade-Engine-Public#36]
source/PlayState.hx:51: characters 8-36 : Type not found : VideoHandler
source/PlayState.hx:52: characters 8-19 : Type not found : VideoSprite
source/PlayState.hx:360: characters 24-35 : Type not found : VideoSprite
source/Debug.hx:24: lines 24-349 : Defined in this class
source/PlayState.hx:333: characters 2-51 : Method set_scrollSpeed required by property scrollSpeed is missing
source/Stage.hx:98: characters 25-38 : PlayState has no field precacheThing
source/Stage.hx:99: characters 25-38 : PlayState has no field precacheThing
source/OptionsMenu.hx:503: characters 26-40 : PlayState has no field updateSettings
source/PauseSubState.hx:247: characters 20-31 : Class<PlayState> has no field luaModchart
source/PauseSubState.hx:249: characters 17-28 : Class<PlayState> has no field luaModchart
source/PauseSubState.hx:250: characters 17-28 : Class<PlayState> has no field luaModchart
source/LuaClass.hx:467: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:519: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:493: characters 22-33 : PlayState has no field createTween
source/ModchartState.hx:295: characters 22-34 : PlayState has no field removeObject
source/ModchartState.hx:297: characters 22-31 : PlayState has no field addObject
source/ModchartState.hx:305: characters 22-34 : PlayState has no field removeObject
source/ModchartState.hx:307: characters 22-31 : PlayState has no field addObject
source/ModchartState.hx:333: characters 22-31 : PlayState has no field addObject
source/ModchartState.hx:388: characters 24-36 : PlayState has no field removeObject
source/ModchartState.hx:389: characters 24-36 : PlayState has no field removeObject
source/ModchartState.hx:390: characters 24-36 : PlayState has no field removeObject
source/ModchartState.hx:392: characters 23-32 : PlayState has no field addObject
source/ModchartState.hx:395: characters 24-33 : PlayState has no field addObject
source/ModchartState.hx:396: characters 24-33 : PlayState has no field addObject
source/ModchartState.hx:397: characters 24-33 : PlayState has no field addObject
source/LuaClass.hx:1931: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1993: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1962: characters 22-33 : PlayState has no field createTween
source/ModchartState.hx:501: characters 23-36 : PlayState has no field precacheThing
source/ModchartState.hx:514: characters 23-45 : PlayState has no field backgroundOverlayVideo
source/ModchartState.hx:578: characters 23-40 : PlayState has no field changeScrollSpeed
source/ModchartState.hx:615: characters 23-40 : PlayState has no field addShaderToCamera
source/ModchartState.hx:620: characters 23-40 : PlayState has no field addShaderToCamera
source/ModchartState.hx:625: characters 23-40 : PlayState has no field addShaderToCamera
source/ModchartState.hx:630: characters 23-40 : PlayState has no field addShaderToCamera
source/ModchartState.hx:635: characters 23-40 : PlayState has no field addShaderToCamera
source/ModchartState.hx:640: characters 23-44 : PlayState has no field clearShaderFromCamera
source/LuaClass.hx:869: characters 39-50 : PlayState has no field createTween
source/LuaClass.hx:882: characters 39-50 : PlayState has no field createTween
source/LuaClass.hx:976: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:918: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1001: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:945: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:2171: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1235: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1270: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1332: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1301: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1580: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1642: characters 22-33 : PlayState has no field createTween
source/LuaClass.hx:1611: characters 22-33 : PlayState has no field createTween
source/Stage.hx:976: characters 27-37 : PlayState has no field endingSong
source/Stage.hx:746: characters 39-50 : PlayState has no field createTween
source/Stage.hx:757: characters 26-37 : PlayState has no field createTween
source/Stage.hx:961: characters 23-34 : PlayState has no field createTimer

What happened? I have all libraries and git hxCodec

**Comment by BoloVEVO** [comment]
oops sorry for the troll bot, open a new issue

**Comment by BoloVEVO** [comment]
Did you change something inside the code?

**Comment by BoloVEVO** [comment]
bro just died.
